---
- import_tasks: zsh.yml

- name: Install power user packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ power_user_packages }}"
  tags:
    - packages
    - power_user

- name: Install monitoring and performance packages
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop: "{{ monitoring_and_performance }}"
  tags:
    - packages
    - monitoring_and_performance

# copy file static-content/vimrc to users ~/.vimrc
- name: Copy .vimrc to user's home directory
  become: false
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/static-content/vimrc"
    dest: /home/{{ ansible_user }}/.vimrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    backup: true
    force: false

- import_tasks: iosevka-font.yml
