# roles/power_user/tasks/zsh.yml
---
# Add this debug task before the existing tasks to verify variables
- name: Debug user variables
  ansible.builtin.debug:
    msg:
      - "ansible_user: {{ ansible_user }}"

# task to install zsh
- name: Install zsh
  become: true
  ansible.builtin.dnf:
    name: zsh
    state: present

# task to change user shell to zsh
- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Configure ZSH and plugins
  become: false
  block:
    - name: Ensure .zshrc file exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.zshrc
        state: touch
        mode: "0644"

    - name: Install Oh My Zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: /home/{{ ansible_user }}/.oh-my-zsh

    - name: Install zsh-autosuggestions plugin # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        depth: 1