---
# tasks for developer role
- name: Install developer packages
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - python3
      - python3-pip
    state: present

- name: Install golang
  become: true
  ansible.builtin.dnf:
    name:
      - golang
    state: present

- name: Install elixir
  become: true
  ansible.builtin.dnf:
    name:
      - erlang
      - elixir
      - elixir-doc
      - erlang-doc
    state: present

# install ruby and rails with rbenv
- name: Install rbenv
  become: true
  ansible.builtin.dnf:
    name:
      - rbenv
      - ruby-build
    state: present

- name: Ruby environment setup
  become: false
  block:
    # add a line to .zshrc to load rbenv
    - name: Add rbenv to .zshrc
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        regexp: ^eval "\$\(rbenv init -\)"
        line: eval "$(rbenv init -)"
      notify: Reload zsh

    # install latest version of ruby with rbenv
    - name: Install ruby
      ansible.builtin.command: rbenv install {{ ruby_version }}
      args:
        creates: /home/{{ ansible_user }}/.rbenv/versions/{{ ruby_version }}

    # set the global version of ruby to 3.1.2
    - name: Set global ruby version
      ansible.builtin.command: rbenv global 3.1.2
    - name: Install rails
      ansible.builtin.command: gem install rails
      args:
        creates: /home/{{ ansible_user }}/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rails-

- name: Install flatpack
  become: true
  ansible.builtin.dnf:
    name:
      - flatpak
    state: present

- name: Install podman
  become: true
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: Install podman-desktop
  become: false
  ansible.builtin.command: flatpak install flathub io.podman_desktop.PodmanDesktop
- name: Add Microsoft GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VS Code repository
  become: true
  ansible.builtin.copy:
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/vscode.repo

- name: Install VS Code
  become: true
  ansible.builtin.dnf:
    name: code
    state: present

- name: Install gitnuro (git GUI)
  become: false
  ansible.builtin.command: flatpak install flathub com.jetpackduba.Gitnuro
