---
# tasks for developer role
- name: Install developer packages
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - python3
      - python3-pip
    state: present

- name: Install golang
  become: true
  ansible.builtin.dnf:
    name:
      - golang
    state: present

- name: Install elixir
  become: true
  ansible.builtin.dnf:
    name:
      - erlang
      - elixir
      - elixir-doc
      - erlang-doc
    state: present

- import_tasks: ruby_and_rails.yml

- name: Install flatpack
  become: true
  ansible.builtin.dnf:
    name:
      - flatpak
    state: present

- name: Install gitnuro (git GUI)
  become: false
  ansible.builtin.command: flatpak install -y flathub com.jetpackduba.Gitnuro

- name: Install podman
  become: true
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: Install podman-desktop
  become: false
  ansible.builtin.command: flatpak install -y flathub io.podman_desktop.PodmanDesktop
 
- import_tasks: vs_code.yml