---
# tasks for developer role
- name: Install developer packages
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - python3
      - python3-pip
    state: present

- name: Install golang
  become: true
  ansible.builtin.dnf:
    name:
      - golang
    state: present

- name: Install elixir
  become: true
  ansible.builtin.dnf:
    name:
      - erlang
      - elixir
      - elixir-doc
      - erlang-doc
    state: present

- import_tasks: ruby_and_rails.yml

- name: Install flatpack
  become: true
  ansible.builtin.dnf:
    name:
      - flatpak
    state: present

- name: Add Flathub repository
  become: false
  ansible.builtin.command: flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Update Flatpak repositories
  become: false
  ansible.builtin.command: flatpak --user update

- name: Install gitnuro (git GUI)
  become: false
  ansible.builtin.command: flatpak --user install -y flathub com.jetpackduba.Gitnuro
  register: gitnuro_install
  retries: 3
  delay: 5
  until: gitnuro_install is not failed
  ignore_errors: true

- name: Notify user if gitnuro installation failed
  ansible.builtin.debug:
    msg: "Gitnuro installation failed after 3 retries."
  when: gitnuro_install is failed

- name: Install podman
  become: true
  ansible.builtin.dnf:
    name:
      - podman
    state: present

- name: Install podman-desktop
  become: false
  ansible.builtin.command: flatpak --user install -y flathub io.podman_desktop.PodmanDesktop
  register: podman_desktop_install
  retries: 3
  delay: 5
  until: podman_desktop_install is not failed
  ignore_errors: true

- name: Notify user if podman-desktop installation failed
  ansible.builtin.debug:
    msg: "Podman Desktop installation failed after 3 retries"
  when: podman_desktop_install is failed

- import_tasks: vs_code.yml