---
# tasks for developer role
- name: Install developer packages
  become: true
  dnf:
    name:
      - gcc
      - make
      - python3
      - python3-pip
    state: present

# TODO get nvm installed and latest node.js installed

# - name: Install node version manager
#   shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#   args:
#     creates: /home/{{ ansible_user }}/nvm

# - name: Install node.js
#   shell: source /home/{{ ansible_user }}/nvm/nvm.sh && nvm install node
#   args:
#     creates: /home/{{ ansible_user }}/.nvm

- name: Install golang
  become: true
  dnf:
    name:
      - golang
    state: present

- name: Install elixir
  become: true
  dnf:
    name:
      - erlang
      - elixir
      - elixir-doc
      - erlang-doc
    state: present

# install ruby and rails with rbenv
- name: Install rbenv
  become: true
  dnf:
    name:
      - rbenv
      - ruby-build
    state: present

# add a line to .zshrc to load rbenv
- name: Add rbenv to .zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: '^eval "\$\(rbenv init -\)"'
    line: 'eval "$(rbenv init -)"'
  notify: reload zsh

# install latest version of ruby with rbenv
- name: Install ruby
  shell: rbenv install {{ ruby_version }}
  args:
    creates: /home/{{ ansible_user }}/.rbenv/versions/{{ ruby_version }}

# set the global version of ruby to 3.1.2
- name: Set global ruby version
  shell: rbenv global 3.1.2

# install rails
- name: Install rails
  shell: gem install rails
  args:
    creates: /home/{{ ansible_user }}/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rails-

# TODO - name: Install AWS cli tools
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
#   become: true
#   dnf:
#     name:
#       - aws-cli
#     state: present

- name: Install podman
  become: true
  dnf:
    name:
      - podman
    state: present

- name: Install flatpack
  become: true
  dnf:
    name:
      - flatpak
    state: present

- name: Install podman-desktop
  become: false
  command: flatpak install flathub io.podman_desktop.PodmanDesktop

- name: Add Microsoft GPG key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add VS Code repository
  become: true
  copy:
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/vscode.repo

- name: Install VS Code
  become: true
  dnf:
    name: code
    state: present

- name: Install gitnuro (git GUI)
  become: false
  command: flatpak install flathub com.jetpackduba.Gitnuro
