---
- name: Ruby and rails environment setup
  become: false
  block:
    - name: Install rbenv
      become: true
      ansible.builtin.dnf:
        name:
          - rbenv
          - ruby-build
          - ruby-devel
        state: present

    - name: Add rbenv to .zshrc
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        regexp: ^eval "\$\(rbenv init -\)"
        line: eval "$(rbenv init -)"
      notify: Reload zsh

    - name: Install ruby
      ansible.builtin.command: rbenv install {{ ruby_version }}
      args:
        creates: /home/{{ ansible_user }}/.rbenv/versions/{{ ruby_version }}

    - name: Set global ruby version
      ansible.builtin.command: rbenv global {{ ruby_version }}
    
    - name: Rehash rbenv
      ansible.builtin.command: rbenv rehash

    - name: Install Rails gem using rbenv
      ansible.builtin.shell: |
        eval "$(rbenv init -)"
        gem install rails -v '>= 7.2'
      args:
        executable: /bin/bash
        
    - name: Check installed Rails version
      ansible.builtin.shell: |
        eval "$(rbenv init -)"
        if gem list -i '^rails$' > /dev/null; then
          rails_version=$(rails -v | awk '{print $2}')
          if [ "$(printf '%s\n' "7.2" "$rails_version" | sort -V | head -n1)" = "7.2" ]; then
            echo "Rails version is greater than or equal to 7.2"
          else
            echo "Rails version is less than 7.2"
            exit 1
          fi
        else
          echo "Rails is not installed"
          exit 1
        fi