filetype on
filetype plugin on
filetype indent on
syntax on
set number
set cursorline
set tabstop=4
set expandtab
set nowrap
set incsearch
set ignorecase
set ruler
set smartcase
set showmatch
set hlsearch