---
- hosts: localhost
  become: true

  vars_files:
    - vars/git_user_vars.yml
    - vars/global_vars.yml

  pre_tasks:
    - name: Get global git username
      command: git config --global user.name
      register: git_user_name
      ignore_errors: true

    - name: Get global git user email
      command: git config --global user.email
      register: git_user_email
      ignore_errors: true

    - name: Set git_user_name variable
      set_fact:
        git_user_name: "{{ git_user_name.stdout if git_user_name.stdout else 'Set Your Git User Name' }}"

    - name: Check if git_user_name is set to default
      set_fact:
        prompt_for_git_user_name: "{{ git_user_name == 'Set Your Git User Name' }}"

    - name: Prompt for Git user name
      pause:
        prompt: "Enter your name for Git"
      register: git_user_name_input
      when: prompt_for_git_user_name

    - name: Set Git user name from input
      set_fact:
        git_user_name: "{{ git_user_name_input.user_input }}"
      when: prompt_for_git_user_name

    - name: Check if git_user_email is set to default
      set_fact:
        prompt_for_git_user_email: "{{ git_user_email == 'set.your.email@example.com' }}"

    - name: Prompt for Git user email
      pause:
        prompt: "Enter your Git user email"
      register: git_user_email_input
      when: prompt_for_git_user_email

    - name: Set Git user email from input
      set_fact:
        git_user_email: "{{ git_user_email_input.user_input }}"
      when: prompt_for_git_user_email

  roles:
    - git_user
    - power_user
    - amateur_radio
    - app_user
    - developer
    - ai_researcher
    - database_engineer
    # communicator
