---
- name: Configure workstation
  hosts: localhost
  become: true

  vars_files:
    - vars/global_vars.yml

  pre_tasks:

    - name: Set up ansible_user
      become: false
      block:
      - name: Get current username
        ansible.builtin.command: id -un
        register: current_user
        changed_when: false

      - name: Set ansible_user fact
        ansible.builtin.set_fact:
          ansible_user: "{{ current_user.stdout }}"

      - name: Debug ansible_user
        ansible.builtin.debug:
          msg: "Current user: {{ ansible_user }}"

  roles:
    - git_user
    - ssh_user
    - power_user
    - app_user
    - amateur_radio
    - developer
    - ai_researcher
    - database_engineer
    - communicator
    # - security - not yet implemented
