---
# tasks for installing communications applications

# make sure system has flatpak installed
- name: Install flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Install Slack
  become: true
  community.general.flatpak:
    name: com.slack.Slack
    state: present
  register: slack_install
  retries: 3
  delay: 5
  until: slack_install is not failed
  ignore_errors: true

- name: Notify user if Slack installation failed
  ansible.builtin.debug:
    msg: "Slack installation failed after 3 retries."
  when: slack_install is failed

- name: Install Discord
  become: true
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
  register: discord_install
  retries: 3
  delay: 5
  until: discord_install is not failed
  ignore_errors: true

- name: Notify user if Discord installation failed
  ansible.builtin.debug:
    msg: "Discord installation failed after 3 retries."
  when: discord_install is failed

- name: Install Zoom
  become: true
  community.general.flatpak:
    name: us.zoom.Zoom
    state: present
  register: zoom_install
  retries: 3
  delay: 5
  until: zoom_install is not failed
  ignore_errors: true

- name: Notify user if Zoom installation failed
  ansible.builtin.debug:
    msg: "Zoom installation failed after 3 retries."
  when: zoom_install is failed

# make sure that the microsoft repo for edge is installed
- name: Add Microsoft Edge repository
  become: true
  ansible.builtin.copy:
    content: |
      [microsoft-edge]
      name=Microsoft Edge
      baseurl=https://packages.microsoft.com/yumrepos/edge
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/microsoft-edge.repo

- name: Install Microsoft Edge
  become: true
  ansible.builtin.dnf:
    name: microsoft-edge-stable
    state: present
