# tasks for installing communications applications

# # make sure system has flatpak installed
# - name: Install flatpak
#   become: true
#   dnf:
#     name: flatpak
#     state: present

# # flatpack install of Slack
# - name: Install Slack
#   become: true
#   flatpak:
#     name: slack
#     state: present

# # flatpack install of Discord
# - name: Install Discord
#   become: true
#   flatpak:
#     name: discord
#     state: present

# # task to install Zoom
# - name: Install Zoom
#   become: true
#   dnf:
#     name: https://zoom.us/client/latest/zoom_x86_64.rpm
#     state: present

# # task to install Microsoft Edge
# - name: Install Microsoft Edge
#   become: true
#   dnf:
#     name: https://packages.microsoft.com/yumrepos/edge/edge-release.rpm
#     state: present


