---
# tasks for installing communications applications

# make sure system has flatpak installed
- name: Install flatpak
  become: true
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Install Slack
  become: true
  community.general.flatpak:
    name: com.slack.Slack
    state: present

- name: Install Discord
  become: true
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install Zoom
  become: true
  community.general.flatpak:
    name: us.zoom.Zoom
    state: present

# make sure that the microsoft repo for edge is installed
- name: Add Microsoft Edge repository
  become: true
  ansible.builtin.copy:
    content: |
      [microsoft-edge]
      name=Microsoft Edge
      baseurl=https://packages.microsoft.com/yumrepos/edge
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/microsoft-edge.repo

- name: Install Microsoft Edge
  become: true
  ansible.builtin.dnf:
    name: microsoft-edge-stable
    state: present
