---
# tasks for installing amateur radio related applications
- name: Install amateur radio applications
  become: true
  ansible.builtin.dnf:
    name:
      - qrq
      - openscad
      - kicad
    state: present
