---
- name: Include pre-tasks
  include_tasks: pre_tasks/pre_tasks.yml

# install git

- name: Debug - top of file
  ansible.builtin.debug:
    msg: Installing git tools

- name: Install Git
  become: true
  ansible.builtin.dnf:
    name:
      - git
      - gitk
      - git-gui
    state: present

- name: Debug - Before configuring git
  ansible.builtin.debug:
    msg: Starting git configuration tasks

# tasks for configuring git

- name: Configure Git settings
  become: false
  block:

    # global config of user.name and user.email are done in the pre_tasks

    - name: Set default Git branch to main
      ansible.builtin.command: git config --global init.defaultBranch main
    - name: Set default merge strategy to rebase
      ansible.builtin.command: git config --global pull.rebase true
    - name: Debug - Before copying global git ignore
      ansible.builtin.debug:
        msg: Copying global git ignore file

    - name: Copy global git ignore file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/global-git-ignore.txt"
        dest: /home/{{ ansible_user }}/.gitignore_global

    # set the global git ignore file
    - name: Set global git ignore file
      ansible.builtin.command: git config --global core.excludesfile "/home/{{ ansible_user }}/.gitignore_global"
    - name: Create git projects directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/Projects
        state: directory
