# tasks for installing user applications
# TODO OBS Studio and OBS Virtual Camera < https://obsproject.com/ >
- name: Install user applications
  become: true
  dnf:
    name:
      - audacity
      - gimp
      - inkscape
      - krita
      - hexchat
      - thunderbird
    state: present

- name: Ensure Pictures directory exists
  file:
    path: "{{ home_dir }}/Pictures/Wallpapers"
    state: directory

# copy background images from project's Wallpapers directory to user's Pictures directory
- name: Copy background images
  copy:
    src: "{{ playbook_dir }}/Wallpapers/"
    dest: "{{ home_dir }}/Pictures/Wallpapers/"
    remote_src: no

# TODO: set the background image to the first image in the Wallpapers directory
# - name: Set background image
#   shell: gsettings set org.gnome.desktop.background picture-uri file://{{ home_dir }}/Pictures/Wallpapers/{{ item }}
#   with_first_found:
#     - files:
#         - "*.jpeg"
#         - "*.jpg"
#         - "*.png"
#         - "*.webp"
#       paths:
#         - "{{ home_dir }}/Pictures/Wallpapers/"
  # notify: reload gnome

