---
# tasks for installing user applications
- name: Install user applications
  become: true
  dnf:
    name:
      - audacity
      - obs-studio
      - gimp
      - inkscape
      - krita
      - hexchat
      - thunderbird
    state: present

- name: Ensure Pictures directory exists
  file:
    path: "/home/{{ ansible_user }}/Pictures/Wallpapers"
    state: directory

# copy background images from project's Wallpapers directory to user's Pictures directory
- name: Copy background images
  copy:
    src: "{{ playbook_dir }}/Wallpapers/"
    dest: "/home/{{ ansible_user }}/Pictures/Wallpapers/"
    remote_src: no

# set the desktop wallpaper to something from the Wallpapers directory
- name: Find first available wallpaper
  find:
    paths: "/home/{{ ansible_user }}/Pictures/Wallpapers"
    patterns: 
      - "*.jpeg"
      - "*.jpg"
      - "*.png"
      - "*.webp"
    file_type: file
  register: wallpaper_files

- name: Pick a random wallpaper
  when: wallpaper_files.matched > 0
  set_fact:
    random_wallpaper: "{{ wallpaper_files.files | random }}"

- name: Set random wallpaper
  when: wallpaper_files.matched > 0
  shell: |
    gsettings set org.gnome.desktop.background picture-uri "file://{{ random_wallpaper.path }}"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://{{ random_wallpaper.path }}"

