---
# tasks for AI researcher role
- name: Install AI researcher packages
  become: true
  dnf:
    name:
      - gcc
      - git
      - python3-devel
      - python3-pip
    state: present

- name: Upgrade pip
  become: false
  pip:
    name: 
      - pip
    extra_args: --upgrade

- name: Install AI Python packages
  become: false
  pip:
    name:
      - numpy
      - pandas
      - scikit-learn
      # - tensorflow
      - keras
      - matplotlib
      - ggplot
      - bokeh

# TODO tensorflow ?
# https://idroot.us/install-tensorflow-fedora-41/