---
# tasks for AI researcher role
- name: Install AI researcher packages
  become: true
  ansible.builtin.dnf:
    name:
      - gcc
      - git
      - python3-devel
      - python3-pip
    state: present

- name: Upgrade pip
  become: false
  ansible.builtin.pip:
    name:
      - pip
    extra_args: --upgrade

- name: Install AI Python packages
  become: false
  ansible.builtin.pip:
    name:
      - numpy
      - pandas
      - scikit-learn
      - keras
      - matplotlib
      - ggplot
      - bokeh
