---
# tasks for AI researcher role
- name: Install AI researcher packages
  become: true
  dnf:
    name:
      - python3
      - python3-pip
    state: present

- name: Install AI Python packages
  become: true
  pip:
    name:
      - numpy
      - pandas
      - scikit-learn
      - tensorflow
      - keras
      - matplotlib
      - ggplot
      - bokeh