---
# tasks for database engineer role
# probably wouldn't install any of the servers, but rather use them in podman containers
# I do however, want the client software for postgresql, mysql, redis, and mongodb (like mongosh)

- name: Install database clients and tools
  become: true
  dnf:
    name:
      - pgcli
      - pgadmin4
      - mycli
      - valkey
      - valkey-doc
    state: present

# TODO add a linked? task file for mongodb
# https://idroot.us/install-mongodb-fedora-41/

# TODO install dbeaver
# https://dbeaver.io/download/
