---
# tasks for database engineer role
# probably wouldn't install any of the servers, but rather use them in podman containers
# I do however, want the client software for postgresql, mysql, redis, and mongodb (like mongosh)

- name: Install database clients and tools
  become: true
  dnf:
    name:
      - pgcli
      - mycli
      - valkey
      - valkey-doc
    state: present

# add repository for pgadmin4
- name: Add pgadmin4 repository
  become: true
  dnf:
    name: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-fedora-repo-2-1.noarch.rpm
    state: present

- name: Install pgadmin4
  become: true
  dnf:
    name: 
      - pgadmin4
      - pgadmin4-desktop
    state: present

# TODO add a linked? task file for mongodb
# https://idroot.us/install-mongodb-fedora-41/

# TODO install dbeaver
# https://dbeaver.io/download/
